### ISSUE TITLE
the international sanctions

### ISSUE THREAD

**Issue by finlabs100** [austinksmith/DontTread#2]
the international sanctions on the north {north korea} has made a huge dent in their funding but North Korea enslaves their own people and makes them work in their factory's  to build machines of war and munitions.     [](url)

**Comment by austinksmith** [comment]
What does North Korea or sanctions have to due with mass surveillance of citizens in the united states?

**Comment by finlabs100** [comment]
it doesn't but it is important for people to know all of the threats to
their security and how to fight against it. If you need to discuss mass
surveillance try looking up NSA and get back to me as soon as possible.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
